### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by KevinTss** [dance-app/api#1]
# Objective

Implement secure authentication for users accessing the app.

# Solution

### User Account Model

Your User model represents the core user entity. Each user has an id, fullName, and can be associated with multiple Account entries.
The Account model stores information related to authentication providers (e.g., local (email + password), Google, Facebook).

In this scope, we will only support local connection for the MVP, but in the future, we will add Google, Facebook,... So the model should be ready to accept that.

You can already check the current [schema](https://github.com/dance-app/api/blob/main/prisma/schema.prisma#L13-L44) for a better understanding.

# Tasks

- [ ] Create POST for user signing up
- [ ] Create POST for user login
- [ ] Create POST for user logout

Use JWT (JSON Web Tokens) for session management and store the token inside the DB.
(If we manually remove the token from the DB, it will logout user)

Note*
You can see that those works are partially done, complete them and make sure the authentication works as expected.
