### ISSUE TITLE
Users management

### ISSUE THREAD

**Issue by KevinTss** [dance-app/api#2]
# Objective

Implement a CRUD of users for admins.

# Solution

This would be all routes which will let us handle users, all those route should be accessible only for user with role ADMIN.

Here is the Role schema:

```
// No roles means -> Student, every user can assist event of browser events
enum Role {
  ADMIN
  TEACHER
  // If you think is necessary to have the `STUDENT` role, feel free to explain why
}
```

`ADMIN`: Represents an administrator with full access to manage the app.
`TEACHER`: Denotes a dance teacher who can create and manage dance events.
`STUDENT`: Refers to a student who attends dance classes. (no role)

# Tasks

- [ ] Implement `Role` to User schema
- [ ] Implement permission concept
- [ ] Create GET /users -> List of users (findAll)
- [ ] Create GET /users/:id -> A single user (findOne)
- [ ] Create POST /users -> Create a new user (create)
- [ ] Create PATCH /users/:id -> Update an user (update)
- [ ] Create DELETE /users/:id -> Delete an user (delete)
